# this is a simulation of a prod docker compose file
# the environment set here will be pulled from os.environ.get in settings
version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ./.data/postgres_dev:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=unsafe

  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    env_file:
      - ./django-polls/.env
    depends_on:
      - db

# this is the service of nginx proxy
# static_data: it allows us to create shared between the
# app service and the proxy service
# the app service will run and pull all static in static_root
# which will be seen by this proxy
# ports: as defined in polls.conf
  proxy:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static_data: